### ISSUE TITLE
Add Cell Parameters Flag in stream2mtz

### ISSUE THREAD

**Issue by kmdalton** [rs-station/careless#51]
Enhancement suggested by @madanmx in https://github.com/Hekstra-Lab/careless-examples/issues/4

**Comment by JBGreisman** [comment]
`stream2mtz` defaults to using the target cell that was provided to `crystfel`. This behavior is due to the implementation in reciprocalspaceship, which parses this information from the header of the stream file. 

I agree it makes sense to have `stream2mtz` accept unit cell parameters (in addition to the spacegroup argument).

**Comment by madanmx** [comment]
Yes both --cell and --spacegroup will help without default values.
