### ISSUE TITLE
suppress tqdm(-like) output

### ISSUE THREAD

**Issue by DHekstra** [rs-station/careless#97]
I pipe the output from Careless (stdout and stderr) to log files. 99.999% of these consist of waitbar/per-iteration updates. Can we suppress those?

**Comment by kmdalton** [comment]
Are you asking me to implement a flag to suppress the progress bar? I don't think most users will want to do away with the progress bar, because it is helpful. So do you want the option to disable it? 

The code does use `tqdm` under the hood. My understanding is this should only print to `stderr`. So, you should be able to redirect `stdout` without this issue.

**Comment by DHekstra** [comment]
Yes, that looks good.
